version: '3'
services:
  hrh-dwh:
    build:
      context: .
      dockerfile: Dockerfile
    image: hrh-dwh
    container_name: hrh-dwh
    restart: unless-stopped
    env_file: .env
    environment:
      - APP_ENV=${APP_ENV}
      - API_KEY=${API_KEY}
      - API_HTTP_PORT=${API_HTTP_PORT}
      - API_HTTPS_PORT=${API_HTTPS_PORT}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - HRH_API_URL=${HRH_API_URL}
      - HRH_API_KEY=${HRH_API_KEY}
    ports:
      - "${API_HTTP_PORT}:${API_HTTP_PORT}"
      - "${API_HTTPS_PORT}:${API_HTTPS_PORT}"